# Generated by Django 3.2.25 on 2025-04-30 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='original_bag',
            field=models.TextField(blank=True, null=True),
        ),
    ]
